<?php

/**
 * @file
 * Register a Hosting service for NGINX w/ HTTPS.
 */

/**
 * Implements hook_hosting_service().
 */
function hosting_nginx_https_hosting_service() {
  return array(
    'https_nginx' => 'http',
  );
}

/**
 * Implements hook_autoload_info() for Backdrop.
 */
function hosting_nginx_https_autoload_info() {
  return [
    'hostingService_http_https_nginx' => 'hosting_nginx_https.service.inc',
  ];
}
